SELECT * FROM EMPRESA
SELECT * FROM PAISES
SELECT * FROM CIUDADES
SELECT * FROM EMPRESA_GERENTE
SELECT * FROM EMPRESA_SUBGERENTE
SELECT * FROM DIRECTOR_SUCURSAL
SELECT * FROM DIRECTOR_DEPARTAMENTO
SELECT * FROM SUCURSALES
SELECT * FROM DEPARTAMENTOS
SELECT * FROM CARGOS
SELECT * FROM VACANTES
SELECT * FROM CANDIDATOS
SELECT * FROM EMPLEADOS
SELECT * FROM CAPACITACIONES
SELECT * FROM ASISTENCIA_CAPACITACIONES
SELECT * FROM VENDEDORES
SELECT * FROM PROVEEDORES
SELECT * FROM PROVEEDOR_GERENTE
SELECT * FROM CLIENTES
SELECT * FROM CLIENTE_GERENTE
SELECT * FROM PRODUCTOS
SELECT * FROM BODEGAS
SELECT * FROM ORDENES
SELECT * FROM ORDENES_ITEMS

insert into VISTA_EMPRESA_EDIT values ('VENTAS COLOMBIA SAS', 'CR 45 # 187', 5253697)

insert into VISTA_PAISES_EDIT values (1, 'Afganistán', 93)
insert into VISTA_PAISES_EDIT values (1, 'Albania', 355)
insert into VISTA_PAISES_EDIT values (1, 'Alemania', 49)
insert into VISTA_PAISES_EDIT values (1, 'Andorra',	376)
insert into VISTA_PAISES_EDIT values (1, 'Angola', 244)
insert into VISTA_PAISES_EDIT values (1, 'Anguila',	1264)
insert into VISTA_PAISES_EDIT values (1, 'Antártida', 672)
insert into VISTA_PAISES_EDIT values (1, 'Antigua y Barbuda', 1268)
insert into VISTA_PAISES_EDIT values (1, 'Antillas Holandesas',	599)
insert into VISTA_PAISES_EDIT values (1, 'Arabia Saudí', 966)
insert into VISTA_PAISES_EDIT values (1, 'Argelia', 213)
insert into VISTA_PAISES_EDIT values (1, 'Argentina', 54)
insert into VISTA_PAISES_EDIT values (1, 'Armenia', 374)
insert into VISTA_PAISES_EDIT values (1, 'Aruba', 297)
insert into VISTA_PAISES_EDIT values (1, 'Ascension Island', 247)
insert into VISTA_PAISES_EDIT values (1, 'Australia', 61)
insert into VISTA_PAISES_EDIT values (1, 'Austria',	43)
insert into VISTA_PAISES_EDIT values (1, 'Azerbaiyán', 994)
insert into VISTA_PAISES_EDIT values (1, 'Bahamas', 1242)
insert into VISTA_PAISES_EDIT values (1, 'Bahrain', 973)
insert into VISTA_PAISES_EDIT values (1, 'Bangladesh', 880)
insert into VISTA_PAISES_EDIT values (1, 'Barbados', 1246)
insert into VISTA_PAISES_EDIT values (1, 'Belarus', 375)
insert into VISTA_PAISES_EDIT values (1, 'Bélgica', 32)
insert into VISTA_PAISES_EDIT values (1, 'Belize', 501)
insert into VISTA_PAISES_EDIT values (1, 'Benin', 229)
insert into VISTA_PAISES_EDIT values (1, 'Bermuda', 1441)
insert into VISTA_PAISES_EDIT values (1, 'Bhutan', 975)
insert into VISTA_PAISES_EDIT values (1, 'Bolivia', 591)
insert into VISTA_PAISES_EDIT values (1, 'Bosnia y Herzegovina', 387)
insert into VISTA_PAISES_EDIT values (1, 'Botswana', 267)
insert into VISTA_PAISES_EDIT values (1, 'Brasil',	55)
insert into VISTA_PAISES_EDIT values (1, 'Brunei Darussalam', 673)
insert into VISTA_PAISES_EDIT values (1, 'Bulgaria', 359)
insert into VISTA_PAISES_EDIT values (1, 'Burkina Faso', 226)
insert into VISTA_PAISES_EDIT values (1, 'Burundi', 257)
insert into VISTA_PAISES_EDIT values (1, 'Cabo Verde', 238)
insert into VISTA_PAISES_EDIT values (1, 'Camboya', 855)
insert into VISTA_PAISES_EDIT values (1, 'Camerún', 237)
insert into VISTA_PAISES_EDIT values (1, 'Canadá', 1)
insert into VISTA_PAISES_EDIT values (1, 'Chad', 235)
insert into VISTA_PAISES_EDIT values (1, 'Chequia', 420)
insert into VISTA_PAISES_EDIT values (1, 'Chile', 56)
insert into VISTA_PAISES_EDIT values (1, 'China', 86)
insert into VISTA_PAISES_EDIT values (1, 'Chipre', 357)
insert into VISTA_PAISES_EDIT values (1, 'Colombia', 57)
insert into VISTA_PAISES_EDIT values (1, 'Comores, Islas', 269)
insert into VISTA_PAISES_EDIT values (1, 'Costa de Marfil', 225)
insert into VISTA_PAISES_EDIT values (1, 'Costa Rica', 506)
insert into VISTA_PAISES_EDIT values (1, 'Croacia', 385)
insert into VISTA_PAISES_EDIT values (1, 'Cuba', 53)
insert into VISTA_PAISES_EDIT values (1, 'Dinamarca', 45)
insert into VISTA_PAISES_EDIT values (1, 'Djibouti', 253)
insert into VISTA_PAISES_EDIT values (1, 'Dominica', 1767)
insert into VISTA_PAISES_EDIT values (1, 'Ecuador', 593)
insert into VISTA_PAISES_EDIT values (1, 'Egipto', 20)
insert into VISTA_PAISES_EDIT values (1, 'El Salvador', 503)
insert into VISTA_PAISES_EDIT values (1, 'Emiratos Árabes Unidos', 971)
insert into VISTA_PAISES_EDIT values (1, 'Eritrea', 291)
insert into VISTA_PAISES_EDIT values (1, 'Eslovaquia', 421)
insert into VISTA_PAISES_EDIT values (1, 'Eslovenia', 386)
insert into VISTA_PAISES_EDIT values (1, 'España', 34)
insert into VISTA_PAISES_EDIT values (1, 'Estados Federados de Micronesia', 691)
insert into VISTA_PAISES_EDIT values (1, 'Estados Unidos', 1)
insert into VISTA_PAISES_EDIT values (1, 'Estonia', 372)
insert into VISTA_PAISES_EDIT values (1, 'Esvalbard y Jan Mayen', 79)
insert into VISTA_PAISES_EDIT values (1, 'Etiopía', 251)
insert into VISTA_PAISES_EDIT values (1, 'Fiji', 679)
insert into VISTA_PAISES_EDIT values (1, 'Filipinas', 63)
insert into VISTA_PAISES_EDIT values (1, 'Finlandia', 358)
insert into VISTA_PAISES_EDIT values (1, 'Francia', 33)
insert into VISTA_PAISES_EDIT values (1, 'Gabón', 241)
insert into VISTA_PAISES_EDIT values (1, 'Gambia', 220)
insert into VISTA_PAISES_EDIT values (1, 'Georgia', 995)
insert into VISTA_PAISES_EDIT values (1, 'Ghana', 233)
insert into VISTA_PAISES_EDIT values (1, 'Gibraltar', 350)
insert into VISTA_PAISES_EDIT values (1, 'Granada', 473)
insert into VISTA_PAISES_EDIT values (1, 'Grecia',	30)
insert into VISTA_PAISES_EDIT values (1, 'Groenlandia', 299)
insert into VISTA_PAISES_EDIT values (1, 'Guadalupe', 590)
insert into VISTA_PAISES_EDIT values (1, 'Guam', 671)
insert into VISTA_PAISES_EDIT values (1, 'Guatemala', 502)
insert into VISTA_PAISES_EDIT values (1, 'Guernsey', 44)
insert into VISTA_PAISES_EDIT values (1, 'Guinea', 224)
insert into VISTA_PAISES_EDIT values (1, 'Guinea Ecuatorial', 240)
insert into VISTA_PAISES_EDIT values (1, 'Guinea Francesa', 594)
insert into VISTA_PAISES_EDIT values (1, 'Guinea-Bissau', 245)
insert into VISTA_PAISES_EDIT values (1, 'Guyana', 592)
insert into VISTA_PAISES_EDIT values (1, 'Haití', 509)
insert into VISTA_PAISES_EDIT values (1, 'Honduras', 504)
insert into VISTA_PAISES_EDIT values (1, 'Hong Kong', 852)
insert into VISTA_PAISES_EDIT values (1, 'Hungría', 36)
insert into VISTA_PAISES_EDIT values (1, 'India', 91)
insert into VISTA_PAISES_EDIT values (1, 'Indonesia', 62)
insert into VISTA_PAISES_EDIT values (1, 'Irak', 964)
insert into VISTA_PAISES_EDIT values (1, 'Irán', 98)
insert into VISTA_PAISES_EDIT values (1, 'Isla Navidad', 61)
insert into VISTA_PAISES_EDIT values (1, 'Islandia', 354)
insert into VISTA_PAISES_EDIT values (1, 'Islas Caimán', 345)
insert into VISTA_PAISES_EDIT values (1, 'Islas Cook', 682)
insert into VISTA_PAISES_EDIT values (1, 'Islas de Norte-Mariana', 670)
insert into VISTA_PAISES_EDIT values (1, 'Islas Feroe', 298)
insert into VISTA_PAISES_EDIT values (1, 'Islas Malvinas', 500)
insert into VISTA_PAISES_EDIT values (1, 'Islas Marshall', 692)
insert into VISTA_PAISES_EDIT values (1, 'Islas Norfolk', 672)
insert into VISTA_PAISES_EDIT values (1, 'Islas Salomón', 677)
insert into VISTA_PAISES_EDIT values (1, 'Islas Turks y Caicos', 649)
insert into VISTA_PAISES_EDIT values (1, 'Islas Ultramarinas de Estados Unidos', 808)
insert into VISTA_PAISES_EDIT values (1, 'Islas Vírgenes Británicas', 284)
insert into VISTA_PAISES_EDIT values (1, 'Islas Vírgenes Estadounidenses', 340)
insert into VISTA_PAISES_EDIT values (1, 'Isle of Man', 44)
insert into VISTA_PAISES_EDIT values (1, 'Israel', 972)
insert into VISTA_PAISES_EDIT values (1, 'Italia',	39)
insert into VISTA_PAISES_EDIT values (1, 'Jamaica', 876)
insert into VISTA_PAISES_EDIT values (1, 'Japón',	81)
insert into VISTA_PAISES_EDIT values (1, 'Jersey',	44)
insert into VISTA_PAISES_EDIT values (1, 'Jordania', 962)
insert into VISTA_PAISES_EDIT values (1, 'Kazajstán', 7)
insert into VISTA_PAISES_EDIT values (1, 'Kenia', 254)
insert into VISTA_PAISES_EDIT values (1, 'Kirgistán', 996)
insert into VISTA_PAISES_EDIT values (1, 'Kiribati', 686)
insert into VISTA_PAISES_EDIT values (1, 'Kuwait', 965)
insert into VISTA_PAISES_EDIT values (1, 'Lesoto', 266)
insert into VISTA_PAISES_EDIT values (1, 'Letonia', 371)
insert into VISTA_PAISES_EDIT values (1, 'Libano', 961)
insert into VISTA_PAISES_EDIT values (1, 'Liberia', 231)
insert into VISTA_PAISES_EDIT values (1, 'Libia', 218)
insert into VISTA_PAISES_EDIT values (1, 'Liechtenstein', 41)
insert into VISTA_PAISES_EDIT values (1, 'Lituania', 370)
insert into VISTA_PAISES_EDIT values (1, 'Luxemburgo', 352)
insert into VISTA_PAISES_EDIT values (1, 'Macao', 853)
insert into VISTA_PAISES_EDIT values (1, 'Macedonia', 389)
insert into VISTA_PAISES_EDIT values (1, 'Madagascar', 261)
insert into VISTA_PAISES_EDIT values (1, 'Malasia', 60)
insert into VISTA_PAISES_EDIT values (1, 'Malawi', 265)
insert into VISTA_PAISES_EDIT values (1, 'Maldivas', 960)
insert into VISTA_PAISES_EDIT values (1, 'Mali', 223)
insert into VISTA_PAISES_EDIT values (1, 'Malta', 356)
insert into VISTA_PAISES_EDIT values (1, 'Marruecos', 212)
insert into VISTA_PAISES_EDIT values (1, 'Martinica', 596)
insert into VISTA_PAISES_EDIT values (1, 'Mauricio', 230)
insert into VISTA_PAISES_EDIT values (1, 'Mauritania', 222)
insert into VISTA_PAISES_EDIT values (1, 'Mayote', 269)
insert into VISTA_PAISES_EDIT values (1, 'México',	52)
insert into VISTA_PAISES_EDIT values (1, 'Mianmar', 95)
insert into VISTA_PAISES_EDIT values (1, 'Moldavia', 373)
insert into VISTA_PAISES_EDIT values (1, 'Mónaco', 377)
insert into VISTA_PAISES_EDIT values (1, 'Mongolia', 976)
insert into VISTA_PAISES_EDIT values (1, 'Montserrat', 664)
insert into VISTA_PAISES_EDIT values (1, 'Mozambique', 258)
insert into VISTA_PAISES_EDIT values (1, 'Namibia', 264)
insert into VISTA_PAISES_EDIT values (1, 'Nauru', 674)
insert into VISTA_PAISES_EDIT values (1, 'Nepal', 977)
insert into VISTA_PAISES_EDIT values (1, 'Nicaragua', 505)
insert into VISTA_PAISES_EDIT values (1, 'Níger', 227)
insert into VISTA_PAISES_EDIT values (1, 'Nigeria', 234)
insert into VISTA_PAISES_EDIT values (1, 'Niue', 683)
insert into VISTA_PAISES_EDIT values (1, 'Noruega', 47)
insert into VISTA_PAISES_EDIT values (1, 'Nueva Caledonia', 687)
insert into VISTA_PAISES_EDIT values (1, 'Nueva Zelanda', 64)
insert into VISTA_PAISES_EDIT values (1, 'Omán', 968)
insert into VISTA_PAISES_EDIT values (1, 'Países Bajos', 31)
insert into VISTA_PAISES_EDIT values (1, 'Pakistán', 92)
insert into VISTA_PAISES_EDIT values (1, 'Palau', 680)
insert into VISTA_PAISES_EDIT values (1, 'Palestina', 970)
insert into VISTA_PAISES_EDIT values (1, 'Panamá', 507)
insert into VISTA_PAISES_EDIT values (1, 'Papúa Nueva Guinea', 675)
insert into VISTA_PAISES_EDIT values (1, 'Paraguay', 595)
insert into VISTA_PAISES_EDIT values (1, 'Perú', 51)
insert into VISTA_PAISES_EDIT values (1, 'Pitcairn', 872)
insert into VISTA_PAISES_EDIT values (1, 'Polinesia Francesa', 689)
insert into VISTA_PAISES_EDIT values (1, 'Polonia', 48)
insert into VISTA_PAISES_EDIT values (1, 'Portugal', 351)
insert into VISTA_PAISES_EDIT values (1, 'Puerto Rico', 1)
insert into VISTA_PAISES_EDIT values (1, 'Qatar', 974)
insert into VISTA_PAISES_EDIT values (1, 'Reino Unido', 44)
insert into VISTA_PAISES_EDIT values (1, 'República Centroafricana', 236)
insert into VISTA_PAISES_EDIT values (1, 'República de Corea (Corea del Sur)',	82)
insert into VISTA_PAISES_EDIT values (1, 'República de Irlanda', 353)
insert into VISTA_PAISES_EDIT values (1, 'República del Congo', 242)
insert into VISTA_PAISES_EDIT values (1, 'República Democrática del Congo', 243)
insert into VISTA_PAISES_EDIT values (1, 'República Democrática Popular de Corea (Corea del Norte)', 850)
insert into VISTA_PAISES_EDIT values (1, 'República Democrática Popular de Laos', 856)
insert into VISTA_PAISES_EDIT values (1, 'República Dominicana', 809)
insert into VISTA_PAISES_EDIT values (1, 'República Dominicana', 829)
insert into VISTA_PAISES_EDIT values (1, 'República Dominicana', 849)
insert into VISTA_PAISES_EDIT values (1, 'Reunión', 262)
insert into VISTA_PAISES_EDIT values (1, 'Ruanda', 250)
insert into VISTA_PAISES_EDIT values (1, 'Rumanía', 40)
insert into VISTA_PAISES_EDIT values (1, 'Rusia', 7)
insert into VISTA_PAISES_EDIT values (1, 'Sáhara Occidental', 212)
insert into VISTA_PAISES_EDIT values (1, 'Samoa Americana, Isla', 684)
insert into VISTA_PAISES_EDIT values (1, 'Samoa, Isla', 685)
insert into VISTA_PAISES_EDIT values (1, 'San Marino', 378)
insert into VISTA_PAISES_EDIT values (1, 'San Pedro y Miquelon', 508)
insert into VISTA_PAISES_EDIT values (1, 'San Vincente y Las Granadinas', 784)
insert into VISTA_PAISES_EDIT values (1, 'Santa Helena', 290)
insert into VISTA_PAISES_EDIT values (1, 'Santa Kitts y Nevis', 869)
insert into VISTA_PAISES_EDIT values (1, 'Santa Lucía', 758)
insert into VISTA_PAISES_EDIT values (1, 'Santo Tomé y Príncipe', 239)
insert into VISTA_PAISES_EDIT values (1, 'Senegal', 221)
insert into VISTA_PAISES_EDIT values (1, 'Serbia y Montenegro', 42)
insert into VISTA_PAISES_EDIT values (1, 'Seychelles', 248)
insert into VISTA_PAISES_EDIT values (1, 'Sierra Leona', 232)
insert into VISTA_PAISES_EDIT values (1, 'Singapur', 65)
insert into VISTA_PAISES_EDIT values (1, 'Siria', 963)
insert into VISTA_PAISES_EDIT values (1, 'Somalia', 252)
insert into VISTA_PAISES_EDIT values (1, 'Sri Lanka', 94)
insert into VISTA_PAISES_EDIT values (1, 'Suazilandia', 268)
insert into VISTA_PAISES_EDIT values (1, 'Sudáfrica', 27)
insert into VISTA_PAISES_EDIT values (1, 'Sudán', 249)
insert into VISTA_PAISES_EDIT values (1, 'Suecia', 46)
insert into VISTA_PAISES_EDIT values (1, 'Suiza', 41)
insert into VISTA_PAISES_EDIT values (1, 'Surinám', 597)
insert into VISTA_PAISES_EDIT values (1, 'Tailandia', 66)
insert into VISTA_PAISES_EDIT values (1, 'Taiwán', 886)
insert into VISTA_PAISES_EDIT values (1, 'Tajikistán', 992)
insert into VISTA_PAISES_EDIT values (1, 'Tanzania', 255)
insert into VISTA_PAISES_EDIT values (1, 'Tanzania', 259)
insert into VISTA_PAISES_EDIT values (1, 'Territorio Oceánico de la India Británica', 246)
insert into VISTA_PAISES_EDIT values (1, 'Timor', 670)
insert into VISTA_PAISES_EDIT values (1, 'Timor Leste', 670)
insert into VISTA_PAISES_EDIT values (1, 'Togo', 228)
insert into VISTA_PAISES_EDIT values (1, 'Tokelau', 690)
insert into VISTA_PAISES_EDIT values (1, 'Tongo', 676)
insert into VISTA_PAISES_EDIT values (1, 'Trinidad y Tobago', 868)
insert into VISTA_PAISES_EDIT values (1, 'Túnez', 216)
insert into VISTA_PAISES_EDIT values (1, 'Turkmenistán', 993)
insert into VISTA_PAISES_EDIT values (1, 'Turquía', 90)
insert into VISTA_PAISES_EDIT values (1, 'Tuvalu', 688)
insert into VISTA_PAISES_EDIT values (1, 'Ucrania', 380)
insert into VISTA_PAISES_EDIT values (1, 'Uganda', 256)
insert into VISTA_PAISES_EDIT values (1, 'Unión Soviética', 7)
insert into VISTA_PAISES_EDIT values (1, 'Uruguay', 598)
insert into VISTA_PAISES_EDIT values (1, 'Uzbekistán', 998)
insert into VISTA_PAISES_EDIT values (1, 'Vanuatu', 678)
insert into VISTA_PAISES_EDIT values (1, 'Vaticano', 379)
insert into VISTA_PAISES_EDIT values (1, 'Venezuela', 58)
insert into VISTA_PAISES_EDIT values (1, 'Vietnam', 84)
insert into VISTA_PAISES_EDIT values (1, 'Wallis y Futuna', 681)
insert into VISTA_PAISES_EDIT values (1, 'Yemen', 967)
insert into VISTA_PAISES_EDIT values (1, 'Yugoslavia', 381)
insert into VISTA_PAISES_EDIT values (1, 'Zaire', 243)
insert into VISTA_PAISES_EDIT values (1, 'Zambia', 260)
insert into VISTA_PAISES_EDIT values (1, 'Zimbawe', 26 ) 

/* SÓLO HAY 5 SUCURSALES */
insert into VISTA_CIUDADES_EDIT values (45, 'Bogotá')
insert into VISTA_CIUDADES_EDIT values (42, 'Santiago de Chile')
insert into VISTA_CIUDADES_EDIT values (11, 'Buenos Aires')
insert into VISTA_CIUDADES_EDIT values (168, 'Lima')
insert into VISTA_CIUDADES_EDIT values (54, 'Quito')
insert into VISTA_CIUDADES_EDIT values (237, 'Caracas')

/* SÓLO HAY 1 GERENTE DE LA EMPRESA*/
insert into VISTA_EMPRESA_GERENTE_EDIT values ( 1, 'Alejandro Rodríguez', 53631501, 3123548112, 'alejandro.jimenez@ventascolombia.co', 45,  'Masculino', 1, 1, 1, 7000000, 0)

/* SÓLO HAY 1 SUBGERENTE */
insert into VISTA_EMPRESA_SUBGERENTE_EDIT values ( 1, 1, 'Luisa Fernanda López', 58566182, 3127894150, 'luisa.lopez@ventascolombia.co', 25,  'Femenino', 1, 1, 1, 5000000, 0)

/* SÓLO HAY 5 DIRECTORES DE SUCURSAL, 1 POR SUCURSAL */
insert into VISTA_DIRECTOR_SUCURSAL_EDIT values ( 1, 'Natalia Pérez', 86455525, 3124103020, 'natalia.perez@ventascolombia.co', 'Femenino', 25, 1, 1, 4000000, 0, 0)
insert into VISTA_DIRECTOR_SUCURSAL_EDIT values ( 2, 'Diego Nájar', 93833711, 3127846362, 'diego.najar@ventascolombia.co', 'Masculino', 33, 1, 1, 4000000, 0, 0)
insert into VISTA_DIRECTOR_SUCURSAL_EDIT values ( 3, 'Roberto Reina', 54020711, 312968574, 'roberto.reina@ventascolombia.co', 'Masculino', 41, 1, 1, 4000000, 0, 0)
insert into VISTA_DIRECTOR_SUCURSAL_EDIT values ( 4, 'Sandra Martínez', 54486071, 3124567891, 'sandra.martinez@ventascolombia.co', 'Femenino', 27, 1, 1, 4000000, 0, 0)
insert into VISTA_DIRECTOR_SUCURSAL_EDIT values ( 5, 'Reinaldo Díaz', 51666475, 3112003541, 'reinaldo.diaz@ventascolombia.co', 'Masculino', 22, 1, 1, 4000000, 0, 0)




insert into VISTA_DIRECTOR_DEPARTAMENTO_EDIT values ( 1, 'Alejandro', 11111111, 3123548112, 'maarojasga@una', 'Masc', 25 , 1, 1, 3500000, 0, 0)

insert into VISTA_SUCURSALES_EDIT values ( 1, 1, 'PRAD0', 11111111, 'CR 6 #192SSASD')
insert into VISTA_DEPARTAMENTOS_EDIT values ( 1, 1,'RECURSOS HUMANOS')


insert into VISTA_CARGOS_EDIT values ( 1, 'Reclutador', 3499999, 2400000)

insert into VISTA_VACANTES_EDIT values ( 1, 1)

insert into VISTA_CANDIDATOS_EDIT values ( 1, 'Ale', 1514815151, 'pepito@gmial.com', 31251323, 18, 'fem', 80)

insert into VISTA_EMPLEADOS_EDIT values ( 1, 1514815151, 'arx', 4144144, 'correo', 'fem', 18, 1 ,1, 1 , 245555555, 1, 1)

insert into VISTA_CAPACITACIONES_EDIT values ( 1, 'Segur', '12/20/14 *DÍA-MES-AÑO', 'Soy una descripción')

insert into VISTA_ASISTENCIA_CAPACITACIONES_EDIT values ( 1, 1)

insert into VISTA_VENDEDORES_EDIT values ( 1, 11012155454, 'RAÚL', 2515551, 'SOY UN CORREO', 'SOY UN GENERO', 18, 1, 1, 2000000, 1, 0, 100000)

insert into VISTA_PROVEEDORES_EDIT values ( 1, 11012155454, 'RAÚL', 2515551, 'SOY UNA DIRECCIÓN', 1, 'SOY UN CORRE0')


insert into VISTA_PROVEEDOR_GERENTE_EDIT values ( 1, 'RAFA', 11012155454, 2515551, 'SOY UN CORRE0')

insert into VISTA_CLIENTES_EDIT values ( 1, 15115515, 'RAFA', 11012155454, 'SOY UNA DIRECCION', 1, 'SOY UN CORRE0')

insert into VISTA_CLIENTE_GERENTE_EDIT values ( 1,'RAFA', 11012155454, 155544144,'SOY UN CORRE0')

insert into VISTA_PRODUCTOS_EDIT values ( 1, 'ARROZ', 1000, 10000)
insert into VISTA_BODEGAS_EDIT values ( 1, 1, 1, 12)

insert into VISTA_ORDENES_EDIT values ( 1, 1, 1, 1, '12/05/20')


insert into VISTA_ORDENES_ITEMS_EDIT values ( 1, 1, 10, 1000000, 0)

