/*==============================================================*/
/* DATOS_TABLA_EMPRESA                                           */
/*==============================================================*/
insert into VISTA_EMPRESA_EDIT values (SECUENCIA_EMPRESA.nextval,'VENTAS COLOMBIA SAS', 'CR 45 # 187', 5253697)

/*==============================================================*/
/* DATOS_TABLA_PAISES                                           */
/*==============================================================*/
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Afganistán', 93);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Albania', 355);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Alemania', 49);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Andorra',	376);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Angola', 244);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Anguila',	1264);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Antártida', 672);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Antigua y Barbuda', 1268);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Antillas Holandesas',	599);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Arabia Saudí', 966);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Argelia', 213);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Argentina', 54);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Armenia', 374);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Aruba', 297);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Ascension Island', 247);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Australia', 61);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Austria',	43);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Azerbaiyán', 994);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bahamas', 1242);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bahrain', 973);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bangladesh', 880);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Barbados', 1246);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Belarus', 375);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bélgica', 32);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Belize', 501);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Benin', 229);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bermuda', 1441);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bhutan', 975);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bolivia', 591);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bosnia y Herzegovina', 387);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Botswana', 267);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Brasil',	55);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Brunei Darussalam', 673);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bulgaria', 359);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Burkina Faso', 226);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Burundi', 257);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Cabo Verde', 238);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Camboya', 855);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Camerún', 237);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Canadá', 1);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Chad', 235);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Chequia', 420);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Chile', 56);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'China', 86);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Chipre', 357);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Colombia', 57);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Comores, Islas', 269);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Costa de Marfil', 225);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Costa Rica', 506);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Croacia', 385);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Cuba', 53);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Dinamarca', 45);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Djibouti', 253);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Dominica', 1767);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Ecuador', 593);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Egipto', 20);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'El Salvador', 503);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Emiratos Árabes Unidos', 971);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Eritrea', 291);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Eslovaquia', 421);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Eslovenia', 386);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'España', 34);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Estados Federados de Micronesia', 691);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Estados Unidos', 1);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Estonia', 372);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Esvalbard y Jan Mayen', 79);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Etiopía', 251);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Fiji', 679);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Filipinas', 63);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Finlandia', 358);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Francia', 33);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Gabón', 241);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Gambia', 220);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Georgia', 995);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Ghana', 233);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Gibraltar', 350);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Granada', 473);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Grecia',	30);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Groenlandia', 299);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guadalupe', 590);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guam', 671);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guatemala', 502);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guernsey', 44);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guinea', 224);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guinea Ecuatorial', 240);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guinea Francesa', 594);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guinea-Bissau', 245);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guyana', 592);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Haití', 509);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Honduras', 504);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Hong Kong', 852);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Hungría', 36);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'India', 91);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Indonesia', 62);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Irak', 964);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Irán', 98);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Isla Navidad', 61);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islandia', 354);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Caimán', 345);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Cook', 682);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas de Norte-Mariana', 670);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Feroe', 298);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Malvinas', 500);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Marshall', 692);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Norfolk', 672);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Salomón', 677);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Turks y Caicos', 649);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Ultramarinas de Estados Unidos', 808);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Vírgenes Británicas', 284);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Vírgenes Estadounidenses', 340);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Isle of Man', 44);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Israel', 972);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Italia',	39);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Jamaica', 876);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Japón',	81);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Jersey',	44);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Jordania', 962);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Kazajstán', 7);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Kenia', 254);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Kirgistán', 996);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Kiribati', 686);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Kuwait', 965);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Lesoto', 266);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Letonia', 371);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Libano', 961);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Liberia', 231);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Libia', 218);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Liechtenstein', 41);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Lituania', 370);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Luxemburgo', 352);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Macao', 853);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Macedonia', 389);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Madagascar', 261);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Malasia', 60);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Malawi', 265);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Maldivas', 960);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mali', 223);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Malta', 356);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Marruecos', 212);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Martinica', 596);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mauricio', 230);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mauritania', 222);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mayote', 269);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'México',	52);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mianmar', 95);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Moldavia', 373);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mónaco', 377);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mongolia', 976);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Montserrat', 664);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mozambique', 258);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Namibia', 264);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nauru', 674);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nepal', 977);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nicaragua', 505);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Níger', 227);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nigeria', 234);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Niue', 683);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Noruega', 47);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nueva Caledonia', 687);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nueva Zelanda', 64);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Omán', 968);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Países Bajos', 31);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Pakistán', 92);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Palau', 680);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Palestina', 970);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Panamá', 507);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Papúa Nueva Guinea', 675);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Paraguay', 595);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Perú', 51);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Pitcairn', 872);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Polinesia Francesa', 689);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Polonia', 48);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Portugal', 351);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Puerto Rico', 1);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Qatar', 974);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Reino Unido', 44);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Centroafricana', 236);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República de Corea (Corea del Sur)',	82);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República de Irlanda', 353);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República del Congo', 242);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Democrática del Congo', 243);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Democrática Popular de Corea (Corea del Norte)', 850);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Democrática Popular de Laos', 856);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Dominicana', 809);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Dominicana', 829);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Dominicana', 849);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Reunión', 262);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Ruanda', 250);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Rumanía', 40);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Rusia', 7);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Sáhara Occidental', 212);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Samoa Americana, Isla', 684);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Samoa, Isla', 685);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'San Marino', 378);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'San Pedro y Miquelon', 508);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'San Vincente y Las Granadinas', 784);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Santa Helena', 290);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Santa Kitts y Nevis', 869);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Santa Lucía', 758);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Santo Tomé y Príncipe', 239);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Senegal', 221);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Serbia y Montenegro', 42);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Seychelles', 248);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Sierra Leona', 232);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Singapur', 65);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Siria', 963);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Somalia', 252);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Sri Lanka', 94);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Suazilandia', 268);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Sudáfrica', 27);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Sudán', 249);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Suecia', 46);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Suiza', 41);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Surinám', 597);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tailandia', 66);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Taiwán', 886);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tajikistán', 992);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tanzania', 255);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tanzania', 259);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Territorio Oceánico de la India Británica', 246);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Timor', 670);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Timor Leste', 670);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Togo', 228);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tokelau', 690);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tongo', 676);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Trinidad y Tobago', 868);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Túnez', 216);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Turkmenistán', 993);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Turquía', 90);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tuvalu', 688);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Ucrania', 380);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Uganda', 256);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Unión Soviética', 7);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Uruguay', 598);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Uzbekistán', 998);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Vanuatu', 678);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Vaticano', 379);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Venezuela', 58);;
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Vietnam', 84);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Wallis y Futuna', 681);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Yemen', 967);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Yugoslavia', 381);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Zaire', 243);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Zambia', 260);
insert into VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Zimbawe', 26 );
