/*==============================================================*/
/* DATOS_TABLA_EMPRESA                                           */
/*==============================================================*/
insert ON VISTA_EMPRESA_EDIT values (SECUENCIA_EMPRESA.nextval,'VENTAS COLOMBIA SAS', 'CR 45 # 187', 5253697)

/*==============================================================*/
/* DATOS_TABLA_PAISES                                           */
/*==============================================================*/
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Afganistán', 93)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Albania', 355)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Alemania', 49)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Andorra',	376)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Angola', 244)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Anguila',	1264)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Antártida', 672)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Antigua y Barbuda', 1268)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Antillas Holandesas',	599)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Arabia Saudí', 966)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Argelia', 213)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Argentina', 54)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Armenia', 374)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Aruba', 297)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Ascension Island', 247)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Australia', 61)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Austria',	43)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Azerbaiyán', 994)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bahamas', 1242)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bahrain', 973)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bangladesh', 880)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Barbados', 1246)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Belarus', 375)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bélgica', 32)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Belize', 501)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Benin', 229)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bermuda', 1441)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bhutan', 975)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bolivia', 591)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bosnia y Herzegovina', 387)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Botswana', 267)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Brasil',	55)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Brunei Darussalam', 673)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Bulgaria', 359)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Burkina Faso', 226)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Burundi', 257)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Cabo Verde', 238)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Camboya', 855)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Camerún', 237)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Canadá', 1)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Chad', 235)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Chequia', 420)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Chile', 56)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'China', 86)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Chipre', 357)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Colombia', 57)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Comores, Islas', 269)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Costa de Marfil', 225)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Costa Rica', 506)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Croacia', 385)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Cuba', 53)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Dinamarca', 45)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Djibouti', 253)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Dominica', 1767)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Ecuador', 593)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Egipto', 20)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'El Salvador', 503)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Emiratos Árabes Unidos', 971)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Eritrea', 291)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Eslovaquia', 421)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Eslovenia', 386)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'España', 34)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Estados Federados de Micronesia', 691)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Estados Unidos', 1)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Estonia', 372)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Esvalbard y Jan Mayen', 79)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Etiopía', 251)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Fiji', 679)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Filipinas', 63)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Finlandia', 358)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Francia', 33)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Gabón', 241)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Gambia', 220)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Georgia', 995)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Ghana', 233)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Gibraltar', 350)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Granada', 473)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Grecia',	30)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Groenlandia', 299)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guadalupe', 590)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guam', 671)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guatemala', 502)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guernsey', 44)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guinea', 224)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guinea Ecuatorial', 240)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guinea Francesa', 594)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guinea-Bissau', 245)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Guyana', 592)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Haití', 509)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Honduras', 504)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Hong Kong', 852)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Hungría', 36)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'India', 91)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Indonesia', 62)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Irak', 964)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Irán', 98)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Isla Navidad', 61)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islandia', 354)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Caimán', 345)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Cook', 682)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas de Norte-Mariana', 670)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Feroe', 298)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Malvinas', 500)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Marshall', 692)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Norfolk', 672)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Salomón', 677)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Turks y Caicos', 649)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Ultramarinas de Estados Unidos', 808)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Vírgenes Británicas', 284)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Islas Vírgenes Estadounidenses', 340)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Isle of Man', 44)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Israel', 972)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Italia',	39)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Jamaica', 876)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Japón',	81)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Jersey',	44)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Jordania', 962)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Kazajstán', 7)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Kenia', 254)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Kirgistán', 996)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Kiribati', 686)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Kuwait', 965)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Lesoto', 266)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Letonia', 371)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Libano', 961)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Liberia', 231)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Libia', 218)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Liechtenstein', 41)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Lituania', 370)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Luxemburgo', 352)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Macao', 853)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Macedonia', 389)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Madagascar', 261)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Malasia', 60)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Malawi', 265)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Maldivas', 960)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mali', 223)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Malta', 356)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Marruecos', 212)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Martinica', 596)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mauricio', 230)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mauritania', 222)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mayote', 269)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'México',	52)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mianmar', 95)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Moldavia', 373)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mónaco', 377)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mongolia', 976)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Montserrat', 664)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Mozambique', 258)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Namibia', 264)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nauru', 674)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nepal', 977)SECUENCIA_PAISES.nextval,
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nicaragua', 505)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Níger', 227)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nigeria', 234)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Niue', 683)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Noruega', 47)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nueva Caledonia', 687)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Nueva Zelanda', 64)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Omán', 968)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Países Bajos', 31)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Pakistán', 92)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Palau', 680)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Palestina', 970)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Panamá', 507)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Papúa Nueva Guinea', 675)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Paraguay', 595)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Perú', 51)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Pitcairn', 872)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Polinesia Francesa', 689)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Polonia', 48)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Portugal', 351)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Puerto Rico', 1)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Qatar', 974)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Reino Unido', 44)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Centroafricana', 236)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República de Corea (Corea del Sur)',	82)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República de Irlanda', 353)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República del Congo', 242)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Democrática del Congo', 243)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Democrática Popular de Corea (Corea del Norte)', 850)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Democrática Popular de Laos', 856)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Dominicana', 809)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Dominicana', 829)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'República Dominicana', 849)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Reunión', 262)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Ruanda', 250)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Rumanía', 40)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Rusia', 7)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Sáhara Occidental', 212)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Samoa Americana, Isla', 684)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Samoa, Isla', 685)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'San Marino', 378)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'San Pedro y Miquelon', 508)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'San Vincente y Las Granadinas', 784)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Santa Helena', 290)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Santa Kitts y Nevis', 869)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Santa Lucía', 758)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Santo Tomé y Príncipe', 239)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Senegal', 221)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Serbia y Montenegro', 42)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Seychelles', 248)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Sierra Leona', 232)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Singapur', 65)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Siria', 963)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Somalia', 252)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Sri Lanka', 94)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Suazilandia', 268)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Sudáfrica', 27)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Sudán', 249)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Suecia', 46)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Suiza', 41)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Surinám', 597)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tailandia', 66)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Taiwán', 886)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tajikistán', 992)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tanzania', 255)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tanzania', 259)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Territorio Oceánico de la India Británica', 246)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Timor', 670)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Timor Leste', 670)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Togo', 228)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tokelau', 690)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tongo', 676)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Trinidad y Tobago', 868)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Túnez', 216)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Turkmenistán', 993)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Turquía', 90)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Tuvalu', 688)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Ucrania', 380)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Uganda', 256)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Unión Soviética', 7)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Uruguay', 598)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Uzbekistán', 998)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Vanuatu', 678)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Vaticano', 379)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Venezuela', 58)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Vietnam', 84)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Wallis y Futuna', 681)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Yemen', 967)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Yugoslavia', 381)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Zaire', 243)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Zambia', 260)
insert ON VISTA_PAISES_EDIT values (SECUENCIA_PAISES.nextval,1, 'Zimbawe', 26 )