/*==============================================================*/
/* Para ORACLE                                             */
/*==============================================================*/

SELECT * FROM ADQUISICION;
SELECT * FROM CARGO;
SELECT * FROM CIUDAD;
SELECT * FROM CLIENTE;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM EMPLEADO;
SELECT * FROM EMPLEADO_VENDEDOR;
SELECT * FROM GERENTE_CLIENTE;
SELECT * FROM GERENTE_PROVEEDOR;
SELECT * FROM PRODUCTO;
SELECT * FROM PROVEEDOR;
SELECT * FROM SUCURSAL;
SELECT * FROM VENDER;

INSERT INTO maarojasga.VISTA_DEPARTAMENTO_EDIT VALUES (1, 'CONTABILIDAD');
INSERT INTO maarojasga.VISTA_DEPARTAMENTO_EDIT VALUES (2, 'MERCADEO');
INSERT INTO maarojasga.VISTA_DEPARTAMENTO_EDIT VALUES (3, 'RECURSOS HUMANOS');


INSERT INTO maarojasga.VISTA_CARGO_EDIT VALUES (1, 1, 'CONTADOR', 3000000);
INSERT INTO maarojasga.VISTA_CARGO_EDIT VALUES (1, 1, 'AUXILIAR CONTABLE', 1500000);
INSERT INTO maarojasga.VISTA_CARGO_EDIT VALUES (3, 3,'psicologo', 2300000);


INSERT INTO maarojasga.VISTA_CIUDAD_EDIT VALUES (1, 1, 'BOGOTÁ');
INSERT INTO maarojasga.VISTA_CIUDAD_EDIT VALUES (2, 1, 'TUNJA');

INSERT INTO maarojasga.VISTA_SUCURSAL_EDIT VALUES (1, 1, 'PRADO');
INSERT INTO maarojasga.VISTA_SUCURSAL_EDIT VALUES (2, 1, 'LOMAS');


INSERT INTO maarojasga.VISTA_EMPLEADO_EDIT VALUES (1, 1, 1, 'ANDRÉS', 'PINZÓN', 3115204571, 'CR 170 #45A', 'MASCULINO', 'AN.PIN@GMAIL.COM', '18/2/2020');


/*=============================== SQL SERVER=============================*/
INSERT INTO dsilvamo.VISTA_DEPARTAMENTO_EDIT VALUES ('CONTABILIDAD');
INSERT INTO dsilvamo.VISTA_DEPARTAMENTO_EDIT VALUES ('MERCADEO');
INSERT INTO dsilvamo.VISTA_DEPARTAMENTO_EDIT VALUES ('RECURSOS HUMANOS');


INSERT INTO dsilvamo.VISTA_CARGO_EDIT VALUES (1, 'CONTADOR', 3000000);
INSERT INTO dsilvamo.VISTA_CARGO_EDIT VALUES (1, 'AUXILIAR CONTABLE', 1500000);
INSERT INTO dsilvamo.VISTA_CARGO_EDIT VALUES (3, 'psicologo', 2300000);


INSERT INTO dsilvamo.VISTA_CIUDAD_EDIT VALUES (1, 'BOGOTÁ');
INSERT INTO dsilvamo.VISTA_CIUDAD_EDIT VALUES (1, 'TUNJA');

INSERT INTO dsilvamo.VISTA_SUCURSAL_EDIT VALUES (1, 'PRADO');
INSERT INTO dsilvamo.VISTA_SUCURSAL_EDIT VALUES (1, 'LOMAS');


INSERT INTO dsilvamo.VISTA_EMPLEADO_EDIT VALUES (1, 1, 'ANDRÉS', 'PINZÓN', 3115204571, 'CR 170 #45A', 'MASCULINO', 'AN.PIN@GMAIL.COM', '18/2/2020');
