CREATE VIEW VISTA_ASISTENCIA_CAPACITACIONES_EDIT
AS
    SELECT
        ASISTENCIA_CAPACITACIONES_ID,
        CAPACITACION_ID,
        ASISTENCIA_CAPACITACIONES_SI_NO_BOOL
    FROM ASISTENCIA_CAPACITACIONES
go

CREATE VIEW VISTA_BODEGAS_EDIT
AS
    SELECT
        BODEGA_ID,
        SUCURSAL_ID,
        BODEGA_CANTIDAD
    FROM BODEGAS
go
CREATE VIEW VISTA_CANDIDATOS_EDIT
AS
    SELECT
        CANDIDATO_ID,
        VACANTE_ID,
        CANDIDATO_NOMBRE,
		CANDIDATO_DOCUMENTO,
		CANDIDATO_CORREO,
		CANDIDATO_CELULAR,
		CANDIDATO_EDAD,
		CANDIDATO_GENERO,
		CANDIDATO_PORCENTAJE_VALORACION		
    FROM CANDIDATOS
go
CREATE VIEW VISTA_CAPACITACIONES_EDIT
AS
    SELECT
        CAPACITACION_ID,
        EMPLEADO_ID,
        CAPACITACION_NOMBRE_TIPO,
		CAPACITACION_FECHA,
		CAPACITACION_DESCRIPCION		
    FROM CAPACITACIONES
go
CREATE VIEW VISTA_CARGOS_EDIT
AS
    SELECT
        CARGO_ID,
        DEPARTAMENTO_ID,
        CARGO_NOMBRE,
		CARGO_SALARIO_MAX,
		CARGO_SALARIO_MIN
    FROM CARGOS
go
CREATE VIEW VISTA_CIUDADES_EDIT
AS
    SELECT
        CIUDAD_ID,
        PAIS_ID,
        CIUDAD_NOMBRE
	FROM CIUDADES
go
CREATE VIEW VISTA_CLIENTE_GERENTE_EDIT
AS
    SELECT
        CLIENTE_GERENTE_ID,
        CLIENTE_ID,
        CLIENTE_GERENTE_NOMBRE,
		CLIENTE_GERENTE_DOCUMENTO,
		CLIENTE_GERENTE_CELULAR,
		CLIENTE_GERENTE_CORREO
    FROM CLIENTE_GERENTE
go
CREATE VIEW VISTA_CLIENTES_EDIT
AS
    SELECT
        CLIENTE_ID,
        CLIENTE_NIT,
        CLIENTE_NOMBRE,
		CLIENTE_CENTRO_LLAMADAS,
		CLIENTE_DIRECCION,
		CLIENTE_NORMAS_BOOL,
		CLIENTE_CORREO
    FROM CLIENTES
go
CREATE VIEW VISTA_DEPARTAMENTOS_EDIT
AS
    SELECT
   DEPARTAMENTO_ID,
   SUCURSAL_ID ,
   DIRECTOR_DEPARTAMENTO_ID,
   DEPARTAMENTO_NOMBRE
    FROM DEPARTAMENTOS
go
CREATE VIEW VISTA_DIRECTOR_DEPARTAMENTO_EDIT
AS
    SELECT
 DIRECTOR_DEPARTAMENTO_ID,
   DIRECTOR_SUCURSAL_ID,
   DIRECTOR_DEPARTAMENTO_NOMBRE,
   DIRECTOR_DEPARTAMENTO_DOCUMENTO,
   DIRECTOR_DEPARTAMENTO_CELULAR,
   DIRECTOR_DEPARTAMENTO_CORREO,
   DIRECTOR_DEPARTAMENTO_GENERO,
   DIRECTOR_DEPARTAMENTO_EDAD
   DIRECTOR_DEPARTAMENTO_SEGURIDAD_SOCIAL_BOOL,
   DIRECTOR_DEPARTAMENTO_POLIZA_VIGENTE_BOOL,
   DIRECTOR_DEPARTAMENTO_SALARIO_FIJO,
   DIRECTOR_DEPARTAMENTO_CONTRATO_INDEFINIDO_BOOL,
   DIRECTOR_DEPARTAMENTO_REINGRESO_BOOL
    FROM DIRECTOR_DEPARTAMENTO
go
CREATE VIEW VISTA_DIRECTOR_SUCURSAL_EDIT
AS
    SELECT
   DIRECTOR_SUCURSAL_ID,
   EMPRESA_SUBGERENTE_ID,
   DIRECTOR_SUCURSAL_NOMBRE,
   DIRECTOR_SUCURSAL_DOCUMENTO,
   DIRECTOR_SUCURSAL_CELULAR,
   DIRECTOR_SUCURSAL_CORREO,
   DIRECTOR_SUCURSAL_GENERO,
   DIRECTOR_SUCURSAL_EDAD,
   DIRECTOR_SUCURSAL_SEGURIDAD_SOCIAL_BOOL,
   DIRECTOR_SUCURSAL_POLIZA_VIGENTE_BOOL,
   DIRECTOR_SUCURSAL_SALARIO_FIJO,
   DIRECTOR_SUCURSAL_CONTRATO_INDEFINIDO_BOOL,
   DIRECTOR_SUCURSAL_REINGRESO_BOOL
    FROM DIRECTOR_SUCURSAL
go
CREATE VIEW VISTA_EMPLEADOS_EDIT
AS
    SELECT
   EMPLEADO_ID,
   CARGO_ID,
   EMPLEADO_DOCUMENTO,
   EMPLEADO_NOMBRE,
   EMPLEADO_CELULAR,
   EMPLEADO_CORREO,
   EMPLEADO_GENERO,
   EMPLEADO_EDAD,
   EMPLEADO_SEGURIDAD_SOCIAL_BOOL,
   EMPLEADO_POLIZA_VIGENTE_BOOL,
   EMPLEADO_CARGO,
   EMPLEADO_SALARIO_FIJO,
   EMPLEADO_CONTRATO_INDEFINIDO_BOOL,
   EMPLEADO_REINGRESO_BOOL
    FROM EMPLEADOS
go
CREATE VIEW VISTA_EMPRESA_EDIT
AS
    SELECT
   EMPRESA_ID,
   EMPRESA_NOMBRE,
   EMPRESA_DIRECCION,
   EMPRESA_CENTRO_LLAMADAS	
    FROM EMPRESA
go
CREATE VIEW VISTA_EMPRESA_GERENTE_EDIT
AS
    SELECT
   EMPRESA_GERENTE_ID,
   EMPRESA_ID,
   EMPRESA_GERENTE_NOMBRE,
   EMPRESA_GERENTE_DOCUMENTO,
   EMPRESA_GERENTE_CELULAR,
   EMPRESA_GERENTE_CORREO 
   EMPRESA_GERENTE_EDAD,
   EMPRESA_GERENTE_GENERO,
   EMPRESA_GERENTE_SEGURIDAD_SOCIAL_BOOL,
   EMPRESA_GERENTE_POLIZA_VIGENTE_BOOL,
   EMPRESA_GERENTE_CONTRATO_INDEFINIDO_BOOL,
   EMPRESA_GERENTE_SALARIO_FIJO,
   EMPRESA_GERENTE_REINGRESO_BOOL
    FROM EMPRESA_GERENTE
go
CREATE VIEW VISTA_EMPRESA_SUBGERENTE_EDIT
AS
    SELECT
   EMPRESA_SUBGERENTE_ID,
   EMPRESA_GERENTE_ID,
   EMPRESA_ID,
   EMPRESA_SUBGERENTE_NOMBRE,
   EMPRESA_SUBGERENTE_DOCUMENTO,
   EMPRESA_SUBGERENTE_CELULAR,
   EMPRESA_SUBGERENTE_CORREO,
   EMPRESA_SUBGERENTE_EDAD,
   EMPRESA_SUBGERENTE_GENERO,
   EMPRESA_SUBGERENTE_SEGURIDAD_SOCIAL_BOOL,
   EMPRESA_SUBGERENTE_POLIZA_VIGENTE_BOOL,
   EMPRESA_SUBGERENTE_CONTRATO_INDEFINIDO_BOOL,
   EMPRESA_SUBGERENTE_SALARIO_FIJO,
   EMPRESA_SUBGERENTE_REINGRESO_BOOL
    FROM EMPRESA_SUBGERENTE
go
CREATE VIEW VISTA_ORDENES_EDIT
AS
    SELECT
   ORDEN_ID,
   SUCURSAL_ID,
   VENDEDOR_ID,
   CLIENTE_ID,
   ORDEN_ESTADO,
   ORDEN_FECHA_SOLICITUD,
   ORDEN_FECHA_ENTREGA 
    FROM ORDENES
go
CREATE VIEW VISTA_ORDENES_ITEMS_EDIT
AS
    SELECT
   ORDEN_ITEM_ID,
   ORDEN_ID,
   PRODUCTO_ID,
   ORDEN_ITEM_CANTIDAD,
   ORDEN_ITEM_PRECIO_TOTAL,
   ORDEN_ITEM_DESCUENTO_BOOL   
    FROM ORDENES_ITEMS
go
CREATE VIEW VISTA_PAISES_EDIT
AS
    SELECT
   PAIS_ID,
   EMPRESA_ID,
   PAIS_NOMBRE,
   PAIS_PREFIJO
    FROM PAISES
go
CREATE VIEW VISTA_PREMIOS_EDIT
AS
    SELECT
   PREMIO_ID,
   PREMIO_NOMBRE,
   PREMIO_VALOR
    FROM PREMIOS
go
CREATE VIEW VISTA_PRODUCTOS_EDIT
AS
    SELECT
   PRODUCTO_ID,
   BODEGA_ID,
   PROVEEDOR_ID,
   PRODUCTO_NOMBRE,
   PRODUCTO_PRECIO_ADQUISICION,
   PRODUCTO_PRECIO_VENTA
    FROM PRODUCTOS
go
CREATE VIEW VISTA_PROVEEDORES_EDIT
AS
    SELECT
   PROVEEDOR_ID,
   PROVEEDOR_NIT,
   PROVEEDOR_NOMBRE,
   PROVEEDOR_CENTRO_LLAMADAS,
   PROVEEDOR_DIRECCION,
   PROVEEDOR_NORMAS_BOOL,
   PROVEEDOR_CORREO
    FROM PROVEEDORES
go
CREATE VIEW VISTA_PROVEEDOR_GERENTE_EDIT
AS
    SELECT
   PROVEEDOR_GERENTE_ID,
   PROVEEDOR_ID,
   PROVEEDOR_GERENTE_NOMBRE,
   PROVEEDOR_GERENTE_DOCUMENTO,
   PROVEEDOR_GERENTE_CELULAR,
   PROVEEDOR_GERENTE_CORREO 
    FROM PROVEEDOR_GERENTE
go
CREATE VIEW VISTA_SUCURSALES_EDIT
AS
    SELECT
   SUCURSAL_ID,
   CIUDAD_ID,
   DIRECTOR_SUCURSAL_ID,
   CLIENTE_ID,
   PROVEEDOR_ID,
   SUCURSAL_NOMBRE,
   SUCURSAL_CENTRO_LLAMADAS,
   SUCURSAL_DIRECCION
    FROM SUCURSALES
go
CREATE VIEW VISTA_VACANTES_EDIT
AS
    SELECT
   VACANTE_ID,
   CARGO_ID,
   VACANTE_NUMERO
    FROM VACANTES
go
CREATE VIEW VISTA_VENDEDORES_EDIT
AS
    SELECT
   VENDEDOR_ID,
   SUCURSAL_ID,
   VENDEDOR_DOCUMENTO,
   VENDEDOR_NOMBRE,
   VENDEDOR_CELULAR,
   VENDEDOR_CORREO,
   VENDEDOR_GENERO,
   VENDEDOR_EDAD,
   VENDEDOR_SEGURIDAD_SOCIAL_BOOL,
   VENDEDOR_POLIZA_VIGENTE_BOOL,
   VENDEDOR_SALARIO_FIJO,
   VENDEDOR_CONTRATO_INDEFINIDO_BOOL,
   VENDEDOR_REINGRESO_BOOL,
   VENDEDOR_COMISION
    FROM VENDEDORES
go
CREATE VIEW VISTA_ASISTENCIA_CAPACITACIONES_View
AS
    SELECT *
    FROM ASISTENCIA_CAPACITACIONES
    WHERE ASISTENCIA_CAPACITACIONES_digitador = user_name()
GO
CREATE VIEW VISTA_BODEGAS_View
AS
    SELECT *
    FROM BODEGAS
    WHERE BODEGA_digitador = user_name()
GO
CREATE VIEW VISTA_CANDIDATOS_View
AS
    SELECT *
    FROM CANDIDATOS
    WHERE CANDIDATO_digitador = user_name()
GO
CREATE VIEW VISTA_CAPACITACIONES_View
AS
    SELECT *
    FROM CAPACITACIONES
    WHERE CAPACITACIONES_digitador = user_name()
GO
CREATE VIEW VISTA_CARGOS_View
AS
    SELECT *
    FROM CARGOS
    WHERE CARGO_digitador = user_name()
GO
CREATE VIEW VISTA_CIUDADES_View
AS
    SELECT *
    FROM CIUDADES
    WHERE CIUDAD_digitador = user_name()
GO
CREATE VIEW VISTA_CLIENTES_View
AS
    SELECT *
    FROM CLIENTES
    WHERE  CLIENTE_digitador = user_name()
GO
CREATE VIEW VISTA_CLIENTE_GERENTE_View
AS
    SELECT *
    FROM CLIENTE_GERENTE
    WHERE  CLIENTE_GERENTE_digitador = user_name()
GO
CREATE VIEW VISTA_DEPARTAMENTOS_View
AS
    SELECT *
    FROM DEPARTAMENTOS
    WHERE   DEPARTAMENTO_digitador = user_name()
GO
CREATE VIEW VISTA_DIRECTOR_DEPARTAMENTO_View
AS
    SELECT *
    FROM DIRECTOR_DEPARTAMENTO
    WHERE   DIRECTOR_DEPARTAMENTO_digitador = user_name()
GO
CREATE VIEW VISTA_DIRECTOR_SUCURSAL_View
AS
    SELECT *
    FROM DIRECTOR_SUCURSAL
    WHERE DIRECTOR_SUCURSAL_digitador = user_name()
GO
CREATE VIEW VISTA_EMPLEADOS_View
AS
    SELECT *
    FROM EMPLEADOS
    WHERE EMPLEADO_digitador = user_name()
GO
CREATE VIEW VISTA_EMPRESA_View
AS
    SELECT *
    FROM EMPRESA
    WHERE EMPRESA_digitador = user_name()
GO
CREATE VIEW VISTA_EMPRESA_GERENTE_View
AS
    SELECT *
    FROM EMPRESA_GERENTE
    WHERE EMPRESA_GERENTE_digitador = user_name()
GO
CREATE VIEW VISTA_EMPRESA_SUBGERENTE_View
AS
    SELECT *
    FROM EMPRESA_SUBGERENTE
    WHERE EMPRESA_SUBGERENTE_digitador = user_name()
GO
CREATE VIEW VISTA_HISTORIAL_TRABAJADORES_View
AS
    SELECT *
    FROM HISTORIAL_TRABAJADORES
GO
CREATE VIEW VISTA_ORDENES_View
AS
    SELECT *
    FROM ORDENES
    WHERE ORDEN_digitador = user_name()
GO
CREATE VIEW VISTA_ORDENES_ITEMS_View
AS
    SELECT *
    FROM ORDENES_ITEMS
    WHERE ORDENES_ITEMS_digitador = user_name()
GO
CREATE VIEW VISTA_PAISES_View
AS
    SELECT *
    FROM PAISES
    WHERE PAIS_digitador = user_name()
GO
CREATE VIEW VISTA_PREMIOS_View
AS
    SELECT *
    FROM PREMIOS
    WHERE PREMIO_digitador = user_name()
GO
CREATE VIEW VISTA_PRODUCTOS_View
AS
    SELECT *
    FROM PRODUCTOS
    WHERE PRODUCTO_digitador = user_name()
GO
CREATE VIEW VISTA_PROVEEDORES_View
AS
    SELECT *
    FROM PROVEEDORES
    WHERE PROVEEDOR_digitador = user_name()
GO
CREATE VIEW VISTA_PROVEEDOR_GERENTE_View
AS
    SELECT *
    FROM PROVEEDOR_GERENTE
    WHERE PROVEEDOR_GERENTE_digitador = user_name()
GO
CREATE VIEW VISTA_SUCURSALES_View
AS
    SELECT *
    FROM SUCURSALES
    WHERE SUCURSAL_digitador = user_name()
GO
CREATE VIEW VISTA_VACANTES_View
AS
    SELECT *
    FROM VACANTES
    WHERE VACANTE_digitador = user_name()
GO
CREATE VIEW VISTA_VENDEDORES_View
AS
    SELECT *
    FROM VENDEDORES
    WHERE VENDEDOR_digitador = user_name()
GO
