
CREATE OR ALTER TRIGGER historia_empleado_insert ON EMPLEADOS
FOR DELETE AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('DELETE EN EMPLEADOS')
    GO

CREATE OR ALTER TRIGGER historia_empleado_insert ON PROVEEDORES
FOR DELETE AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('DELETE EN PROVEEDORES')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON PRODUCTOS
FOR DELETE AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('DELETE EN PRODUCTOS')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON CLIENTES
FOR DELETE AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('DELETE EN CLIENTES')
    GO







CREATE OR ALTER TRIGGER historia_empleado_insert ON EMPLEADOS
FOR UPDATE AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('UPDATE EN EMPLEADOS')
    GO

CREATE OR ALTER TRIGGER historia_empleado_insert ON PROVEEDORES
FOR UPDATE AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('UPDATE EN PROVEEDORES')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON PRODUCTOS
FOR UPDATE AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('UPDATE EN PRODUCTOS')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON CLIENTES
FOR UPDATE AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('UPDATE EN CLIENTES')
    GO







CREATE OR ALTER TRIGGER historia_empleado_insert ON EMPLEADOS
FOR INSERT AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('INSERT EN EMPLEADOS')
    GO

CREATE OR ALTER TRIGGER historia_empleado_insert ON PROVEEDORES
FOR INSERT AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('INSERT EN PROVEEDORES')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON PRODUCTOS
FOR INSERT AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('INSERT EN PRODUCTOS')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON CLIENTES
FOR INSERT AS 
    INSERT INTO REGISTRO_HISTORICO
    (REGISTRO_HISTORICO_MENSAJE)
VALUES
    ('INSERT EN CLIENTES')
    GO

