
CREATE OR ALTER TRIGGER historia_empleado_insert ON EMPLEADOS
FOR DELETE AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'DELETE EN EMPLEADOS')
    GO

CREATE OR ALTER TRIGGER historia_empleado_insert ON PROVEEDORES
FOR DELETE AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'DELETE EN PROVEEDORES')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON PRODUCTOS
FOR DELETE AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'DELETE EN PRODUCTOS')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON CLIENTES
FOR DELETE AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'DELETE EN CLIENTES')
    GO







CREATE OR ALTER TRIGGER historia_empleado_insert ON EMPLEADOS
FOR UPDATE AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'UPDATE EN EMPLEADOS')
    GO

CREATE OR ALTER TRIGGER historia_empleado_insert ON PROVEEDORES
FOR UPDATE AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'UPDATE EN PROVEEDORES')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON PRODUCTOS
FOR UPDATE AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'UPDATE EN PRODUCTOS')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON CLIENTES
FOR UPDATE AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'UPDATE EN CLIENTES')
    GO







CREATE OR ALTER TRIGGER historia_empleado_insert ON EMPLEADOS
FOR INSERT AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'INSERT EN EMPLEADOS')
    GO

CREATE OR ALTER TRIGGER historia_empleado_insert ON PROVEEDORES
FOR INSERT AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'INSERT EN PROVEEDORES')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON PRODUCTOS
FOR INSERT AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'INSERT EN PRODUCTOS')
    GO
CREATE OR ALTER TRIGGER historia_empleado_insert ON CLIENTES
FOR INSERT AS 
    DECLARE @usuario VARCHAR(15)
    DECLARE @fecha DATETIME
    SELECT @fecha=GETDATE()
    SELECT @usuario= user_name() 
    INSERT INTO REGISTRO_HISTORICO
    (
    REGISTRO_HISTORICO_USUARIO,
    REGISTRO_HISTORICO_FECHA,
    REGISTRO_HISTORICO_MENSAJE
    )
VALUES
    (@usuario, @fecha, 'INSERT EN CLIENTES')
    GO

